/**
 * @file StateGame.cpp
 * 
 * @author José Tomás Tocino García
 * @date 2011
 *
 * Copyright (C) 2011 José Tomás Tocino García <theom3ga@gmail.com>
 * 
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
 * 02110-1301, USA.
 */


#include "StateGame.h"
#include "log.h"
#include "ResourceManager.h"
#include "i18n.h"

StateGame::StateGame(){
    lDEBUG << Log::CON("StateGame");
}
StateGame::~StateGame(){
    lDEBUG << Log::DES("StateGame");
}

void StateGame::loadResources(){

    /*****************************************/
    // FONTS

    // Load the font for the timer
    fontTime = ResMgr -> getFont("media/fuentelcd.ttf", 62);

    // Load the font for the scoreboard
    fontScore = ResMgr -> getFont("media/fuentelcd.ttf", 33);

    /*****************************************/
    // IMAGES

    // Load the backgorund image
    spBoard.SetImage(ResMgr -> getImage("media/board.png"));

    // Load the image for the square selector
    spSelector.SetImage(ResMgr -> getImage("media/selector.png"));    

    /*****************************************/
    // SCOREBOARD

    // Load the background image for the scoreboard
    spScoreBackground.SetImage(ResMgr -> getImage("media/scoreBackground.png"));
    spScoreBackground.SetPosition (17, 124);

    // Create the header of the scoreboard
    strScoreHeader = sf::String (_("score"),
                                 ResMgr -> getFont("media/fNormal.ttf", 33),
                                 33);
    strScoreHeader.SetPosition (113 - strScoreHeader.GetRect().GetWidth() / 2, 80);

    /*****************************************/
    // TIME INDICATOR

    // Load the background image for the time indicator
    spTimeBackground.SetImage(ResMgr -> getImage("media/timeBackground.png"));
    spTimeBackground.SetPosition(17, 230);

    // Create the header of the time indicator
    strTimeHeader = sf::String(_("time left"),
                               ResMgr -> getFont("media/fNormal.ttf", 33),
                               33);
    strTimeHeader.SetPosition (113 - strTimeHeader.GetRect().GetWidth() / 2, 186);

}
void StateGame::event (sf::Event theEvent){

}
void StateGame::update (bool isCovered){

}
void StateGame::draw (bool isCovered, DrawingQueue& queue){
    queue.Draw(0, spBoard);
    queue.Draw(1, strScoreHeader);
    queue.Draw(1, spScoreBackground);
    queue.Draw(1, strTimeHeader);
    queue.Draw(1, spTimeBackground);
}

/// Tests if the moouse is over a gem
bool overGem(int mX, int mY){
    return false;
}

/// Returns the coords of the gem the mouse is over
coord getCoord(int mX, int mY){

}

/// Redraws the score board
void redrawScoreboard(){

}

/// Creates a small label that indicates the points generated by a match
void createFloatingScores(){

}
    
/// Check if that gem was clicked
bool checkClickedSquare(int mX, int mY){
    return false;
}

/// Shows a hint for a possible match
void showHint(){

}

/// Plays the sound for the match
void playMatchSound(){

}

/// Resets the game
void resetGame(){

}
